version: '2'

services:
  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d
  web:
    image: kyamamoto03/httpd:latest
    ports:
      - "80:80"
      